backend_rayuela/accounts/urls.py
from django.urls import path
from .views import writer_home, writer_profile, create_user, view_profile, login_writer, logout_writer

app_name='accounts-urls'

urlpatterns = [
    path('', writer_home, name='writer-home'),
    path('profile/', writer_profile, name='writer-profile'),
    path('create/', create_user, name='create-user'),
    path('view-profile/<str:email>', view_profile, name='view-profile'),
    path('login/', login_writer, name='login'),
    path('logout/', logout_writer, name='logout'),
]

backend_rayuela/backend_rayuela/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import preview_page, login_page, logout_page

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', preview_page, name='init-page'),
    path('login/', login_page, name='login-page'),
    path('logout/', logout_page, name='logout-page'),
    path('story/', include('stories.urls', namespace='stories-urls')),
    path('writers/', include('writers.urls', namespace='writers-urls')),
    path('accounts/', include('accounts.urls', namespace='accounts-urls')),
    path('hopscotch', include('hopscotch.urls', namespace='hopscotch-urls')),
    path('stories-routes/', include('stories_routes.urls', namespace='stories-routes-urls'))
]


if settings.DEBUG:
    urlpatterns+= staticfiles_urlpatterns()

backend_rayuela/hopscotch/urls.py
from django.urls import path
from .views import hopscotch_home, hopscotch_create

app_name = 'hopscotch-urls'

urlpatterns = [
    path('home/', hopscotch_home, name='hopscotch-home'),
    path('create/', hopscotch_create, name='hopscotch-create')
]

backend_rayuela/stories/urls.py
from django.urls import path
from .views import story_home ,story_list, story_create, story_delete, story_detail, story_update, all_stories

app_name = 'stories-urls'

urlpatterns = [
    path('home/', story_home, name='story-home'),
    path('create/', story_create, name='story-create'),
    path('list/', story_list, name='story-list'),
    path('story/', story_detail, name='story-detail'),
    path('update/', story_update, name='story-update'),
    path('delete/', story_delete, name='story-delete'),
    path('all-stories', all_stories, name='all-stories')
]

backend_rayuela/stories_routes/urls.py
from django.urls import path
from .views import stories_routes_home, stories_routes_create, all_comments
app_name = 'stories-routes-urls'

urlpatterns=[
    path('home/', stories_routes_home, name='stories-routes-home'),
    path('create/', stories_routes_create, name='stories-routes-create'),
    path('all-comments/', all_comments, name='stories-routes-comments'),
]

backend_rayuela/writers/urls.py
from django.urls import path
from .views import all_comments, create_comment, create_reply_comment, all_comments_tree

app_name='writers-urls'

urlpatterns = [
    path('all-comments/', all_comments, name='all-comments'),
    path('create/', create_comment, name='create-comment'),
    path('create-reply-comment/', create_reply_comment, name='create-reply-comment'),
    path('all-comments-tree/', all_comments_tree, name='all-comments-tree')
]

backend_rayuela/hopscotch/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
#from storie_routes import StoryRoute
# from accounts import models
# Create your models here.


class HopscotchAndStory(models.Model):
    story = models.ForeignKey("stories.Story", on_delete=models.CASCADE)
    hopscotch = models.ForeignKey("Hopscotch", on_delete=models.CASCADE)


class Hopscotch(models.Model):
    title = models.CharField(max_length=30)
    story = models.ManyToManyField("stories.Story", through=HopscotchAndStory)
    state = models.BooleanField(default=True)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)  # Se agrego post-modelo

    class Meta:
        permissions = (
            ("can_be_admin", "Can be admin"),
        )

    def __str__(self):
        return f"{self.id} {self.title}"

    @property
    def get_all(self):
        return f"Autor: {self.writer}\n Story: {self.story}\n State: {self.state}"

backend_rayuela/stories/models.py
from django.db import models
from django.conf import settings


class Story(models.Model):
 #   hopscotch = models.ManyToManyField(Hopscotch)
 #   story_route = models.ManyToManyField(StoryRoute)
    title = models.CharField(max_length=30)
    body = models.CharField(max_length=1024)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)  # Author solamente puede ser uno solo
#    likes = models.CharField()  # puede tener muchos likes de muchos usuarios relacion manyToMany, no se si es necesario este campo
    timestamp = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=200, unique=True, null=True, blank=True)
#    image = models.FileField(upload_to="/images", blank=True, null=True)

    def __str__(self):
      return f"Titulo: {self.title} - contenido: {self.body}"


class Hashtag(models.Model):

   story = models.ForeignKey(Story, on_delete=models.CASCADE)
   hashtag = models.CharField(max_length=30)
   timestamp = models.DateTimeField(auto_now_add=True)


   def __str__(self):
      return f"{self.story.id} - {self.hashtag} - {self.timestamp}"

backend_rayuela/stories_routes/models.py
from django.db import models
from django.conf import settings

class StoryRoute(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    story = models.ForeignKey("stories.Story", on_delete=models.CASCADE)
#    colaborator = models.ManyToManyField(Colaborator)
#   title = models.CharField()

    def __str__(self):
        return f"ID: {self.id}\n STORIES: ROUTE: {self.story}"



class RouteOrder(models.Model):
    story_route = models.ForeignKey(StoryRoute, on_delete=models.CASCADE)
    story_parent = models.ForeignKey("self", null=True, on_delete=models.CASCADE)  # valores positivos
    story_id = models.IntegerField()  # UID de Story

backend_rayuela/hopscotch/forms.py
from django import forms
from .models import Hopscotch, HopscotchAndStory
from stories.models import Story

class HopscotchCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.stories_list = tuple([(story.id, story.title) for story in Story.objects.filter(writer=self.user)])
        super(HopscotchCreateForm, self).__init__(*args, **kwargs)
        self.fields['writer'].initial = self.user
        self.fields['stories'] = forms.MultipleChoiceField(
            label="Elige tus historias",
            widget=forms.CheckboxSelectMultiple, choices=self.stories_list)

    writer = forms.CharField(disabled=True)

    class Meta:
        model = Hopscotch
        fields = '__all__'
        exclude = ('story','writer',)
        labels = {
            "state": "Estado de tu rayuela (Pública o privada)",
        }

    def save(self):
        hopscotch = super().save(commit=False)
        hopscotch.writer = self.user  # dueño de hopscotch
        stories = self.cleaned_data.get('stories')
        hopscotch.save()
        self.save_stories(stories=stories, hopscotch=hopscotch)

    def save_stories(self, stories, hopscotch):
        try:
            for id_story in stories:
                story = Story.objects.get(id=int(id_story))
                added_story = HopscotchAndStory(story=story, hopscotch=hopscotch)
                added_story.save()
        except:
            raise ValueError

backend_rayuela/stories/forms.py
from django import forms
from .models import Story, Hashtag


class StoryCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(StoryCreateForm, self).__init__(*args, **kwargs)
        print(self.user.email)
        self.fields['writer'].initial = self.user

    writer = forms.CharField(label="Writer", disabled=True, widget=forms.TextInput())

    class Meta:
        model = Story
        fields = '__all__'
        exclude = ('writer',)
        widgets = {
            'body': forms.Textarea(attrs={'row': 30, 'col': 30})
        }

    def save(self, commit=True):
        story = super().save(commit=False)
        story.writer = self.user
        if commit:
            story.save()
            self.split_tag(story=story)

    def split_tag(self, story):
        tags = self.cleaned_data.get('tags')
        print("TAGS: ", tags)
        splited_tags = tags.split(" ")
        print("SPLIT:", splited_tags)
        try:
            for hashtag in splited_tags:
                hashtag_model = Hashtag(story=story, hashtag=hashtag)
                hashtag_model.save()
            print("SE GUARDARON LOS HASHTAGS")
        except:
            raise ValueError

backend_rayuela/stories_routes/forms.py
from django import forms
from .models import StoryRoute
from stories.models import Story
'''
class HopscotchCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.stories_list = tuple([(story.id, story.title) for story in Story.objects.filter(writer=self.user)])
        super(HopscotchCreateForm, self).__init__(*args, **kwargs)
        self.fields['writer'].initial = self.user
        self.fields['stories'] = forms.MultipleChoiceField(
            label="Elige tus historias",
            widget=forms.CheckboxSelectMultiple, choices=self.stories_list)

    writer = forms.CharField(disabled=True)

    class Meta:
        model = Hopscotch
        fields = '__all__'
        exclude = ('story','writer',)
        labels = {
            "state": "Estado de tu rayuela (Pública o privada)",
        }

    def save(self):
        hopscotch = super().save(commit=False)
        hopscotch.writer = self.user  # dueño de hopscotch
        stories = self.cleaned_data.get('stories')
        hopscotch.save()
        self.save_stories(stories=stories, hopscotch=hopscotch)

    def save_stories(self, stories, hopscotch):
        try:
            for id_story in stories:
                story = Story.objects.get(id=int(id_story))
                added_story = HopscotchAndStory(story=story, hopscotch=hopscotch)
                added_story.save()
        except:
            raise ValueError

'''
class  StoryRouteCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.stories_list = tuple([(story.id, story.title) for story in Story.objects.filter(writer=self.user)])
        super(StoryRouteCreateForm, self).__init__(*args, **kwargs)  # Actualizo objecto
        self.fields['writer'].initial = self.user
        self.fields['stories'] = forms.MultipleChoiceField(
            label="Elige tus historias",
            widget=forms.CheckboxSelectMultiple, choices=self.stories_list)

    writer = forms.CharField(disabled=True)

    class Meta:
        model = StoryRoute
        fields = ['id']

    def save(self):
        story_route = super().save(commit=False)
        story_route.writer = self.user
        stories = list(map(int, self.cleaned_data.get('stories')))
        print("STORIES:", stories)
        for story in stories:
            story = Story.objects.get(id=story)
            story_route.story = story
            story_route.save()
            print("STORY ROUTE: ",story_route)

#        story_route.story = stories
#        for story in stories:
#            story_route.story = story
#            story_route.save()

backend_rayuela/hopscotch/views.py
from django.shortcuts import render, redirect
from .forms import HopscotchCreateForm
from .models import Hopscotch, HopscotchAndStory
from django.db.models import Count

def hopscotch_home(request, *args, **kwargs):
    '''
        La base de datos sqlite no soporta .distinct() con parametros.
        Para consultas más refinadas se recomienda ocupar POSTGRESQL.

        TODO
            Encontrar una queryset que me permita obtener:
                Cantidad de historias de un cierto hopscotch que pertenece a un cierto usuario.
                - Flujo de ejemplo:
                    - Obtener usuario (request.user)
                    - Filtrar hopscotch por usuario (writer=request.user)
                    - Agregar a cada hopscotch un campo que contenga
                      la cantidad total de historias que están relacionadas.

    '''

    hopscotchs = Hopscotch.objects.filter(writer=request.user)

#    response = Hopscotch.objects.filter(writer=request.user).annotate(count_stories=(

#    ))
#    print("RESPONSE:", response)

#    test = Hopscotch.objects.filter(writer=request.user).first()
#    print("TEST:", test)
#    count = HopscotchAndStory.objects.filter(hopscotch=test).values('story').count()
#    print("COUNT: ", count)
#    numbers_stories = [
#        HopscotchAndStory.objects.filter(hopscotch=hopscotch).count()
#        for hopscotch in hopscotchs
#        ]
#    print("TIPO: ",type(numbers_stories))
#    print("NUMBERS: ", numbers_stories)
    data = {
        "hopscotchs": hopscotchs,
 #       "numbers": numbers_stories
    }
    return render(request, "pages/hopscotch.html", context=data)


def hopscotch_create(request, *args, **kwargs):
    if request.method == "POST":
        form = HopscotchCreateForm(request.POST or None, user=request.user)

        if form.is_valid():
            form.save()
            return redirect("hopscotch-urls:hopscotch-home")
        else:
            data = {"form": form}
            return render(request, "pages/hopscotch.html", context=data)


def hopscotch_update():
    pass

def hopscotch_delete():
    pass

def hopscotch_get():
    pass

def hoptscotch_get_list():
    pass

backend_rayuela/stories/views.py
import json
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Story, Hashtag
from .forms import StoryCreateForm
# Create your views here.

@csrf_exempt
def story_home(request):
#    hashtags = Hashtag.objects.select_related('story__writer').filter(story__writer=Subquery)
    stories = Story.objects.filter(writer=request.user)
#    hastags = response[0].hashtag_set.all()
#    union = response.intersection(hastags)
#    print(response)
#    print(union)
#    user = stories.writer
#    print("STORIES:", stories)
#    print("uSER: ", user)
#    print(hashtags)
#    stories = [story for story in Story.objects.filter(writer=request.user)]
#    for story in stories:
#        total_stories = [hashtag for hashtag in Hashtag.objects.select_related('story').order_by('timestamp')]
#    total_stories = stories.hashtag_set.all()
#    print("TOTAL STORIES: ",total_stories)
#    hashtags = Hashtag.objects.get(story=)
#    print("STORIES: ", stories)
#    print(hashtags)
    data = {
        "stories": stories
    }
    return render(request, "pages/story.html", context=data)

@csrf_exempt
def story_list(request):
    story = Story.objects.all()
    print(story)
    for s in story:
        print(s.writer)
        print(s.timestamp)
    data = {}
    return JsonResponse(data, status=200)


def story_detail(request, *args, **kwargs):
    data = {}
    return JsonResponse(data, status=200)


def all_stories(request, *args, **kwargs):
    return render(request, "pages/story.l", context={})

@csrf_exempt
def story_create(request, *args, **kwargs):
    if request.method == "POST":
        form = StoryCreateForm(request.POST, user=request.user)
        if form.is_valid():
            print(form)
            form.save()
            return redirect("stories-urls:story-home")
        else:
            data = {"form": form}
#    print(request.user.is_valid())
#    data = json.loads(request.body)
#    title = data['title']
#    body = data['body']
#    story = Story(title=title, body=body)
#    story.save()
    return render(request, "pages/story.html", context=data)


def story_update(request, *args, **kwargs):
    data = {}
    return JsonResponse(data, status=200)


def story_delete(request, *args, **kwargs):
    data = {}
    return JsonResponse(data, status=200)

backend_rayuela/stories_routes/views.py
from django.shortcuts import render, redirect
from .forms import StoryRouteCreateForm
from .models import StoryRoute
from writers.models import Comment
# Create your views here.


def stories_routes_home(request):
    stories_routes = StoryRoute.objects.filter(writer=request.user)
    data = {"stories_routes": stories_routes}
    return render(request, "pages/stories_routes.html", context=data)


def stories_routes_create(request):
    if request.method == "POST":
        form = StoryRouteCreateForm(request.POST or None, user=request.user)

        if form.is_valid():
            form.save()
            return redirect('stories-routes-urls:stories-routes-home')

        else:
            data = {"form": form}
            return render(request, "pages/stories_routes.html", context=data)

    return redirect('stories-routes-urls:stories-routes-home')


def all_comments(request):
    print("POST: ",request.POST['comments'])
    id_story_route = request.POST['comments']
    print(id_story_route)
    comments = 1
    data = {"comments": comments}
    return render(request, "pages/stories_routes.html", context=data)

backend_rayuela/templates/pages/all_comments.html
{% for comment in comments %}
    <li>
        {{ comment.id }}

    </li>
{% endfor %}

backend_rayuela/templates/pages/comments.html
{% extends 'pages/home.html' %}
{% block content_login %}
    <h1>HAY COMENTARIOS</h1>
 <div class="all-comments-container" style="text-align: center;">
        <div class="info-comments">
            <p>ESPACIO PARA COLOCAR ESTADISTICA DE COMENTARIOS(?)</p>
        </div>
        <div class="post-comment">
            <p>ESPACIO PARA CREAR COMENTARIO</p>
             <form method="POST" action="{% url 'writers-urls:create-comment' %}">
                <p>
                    {% csrf_token %}
                    <div>ID: {{ story_route.id }}</div>
                    {% for field in form.visible_fields %}
                        <div class="field-container" style="margin-top:2rem; margin-bottom: 2rem;">
                            <div>
                                {{ field.label_tag }}
                            </div>
                            <div>
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                </p>
                <button name="id" value={{ id_story_route }} class="button" type="submit">POSTEAR</button>
            </form>
        </div>
        <div>
            <p>ESPACIO PARA TODO SLOS COMENTARIOS POSTEADOS DEL ID</p>
            <div>
                <p>VER ARBOL DE COMENTARIOS</p>
                <form method="POST" action="{% url 'writers-urls:all-comments-tree' %}">
                    {% csrf_token %}
                    <button>VER ARBOL</button>
                </form>
            </div>
            {% if comments %}
                {% for comment in comments %}
                    <div style="text-align: center; margin: auto; border-style: solid; border-width: 1px; border-radius: 50px;">
                        <div>Story route: {{ comment.story_route.id }}</div>
                        <div>{{ comment.content }}</div>
                        <form method="POST" action="{% url 'writers-urls:create-reply-comment' %}">
                            {% csrf_token %}
                            <input name="content" />
                            <input type="hidden" name="id_story_route" value="{{ comment.story_route.id }}" />
                            <button name="id_reply" value={{ comment.id }} class="button" type="submit">reply comment</button>
                        </form>
                    </div>
                {% endfor %}
            {% else %}
                <h3>SIN COMENTARIOS TODAVIA</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

backend_rayuela/templates/pages/home.html
{% extends 'pages/base.html' %}
{% block content %}

<nav class="nav">
    <div class="nav-ul">
        <p class="nav-li">
            <a clas="nav-link" href="">PUBLIC</a>
        </p>
        <p>
            <a class="nav-link" href="{% url 'stories-urls:story-home' %}">STORIES</a>
        </p>
        <p>
            <a class="nav-link" href="{% url 'hopscotch-urls:hopscotch-home' %}">HOPSCOTCH</a>
        </p>
        <p>
            <a class="'nav-link" href="{% url 'stories-routes-urls:stories-routes-home'%}">STORIES ROUTES</a>
        </p>
        <p>
            <a class="nav-link" href="{% url 'accounts-urls:writer-profile' %}">PROFILE</a>
        </p>
        <p>
            <div class="button-logout">
            <form action="{% url 'accounts-urls:logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit">LOGOUT</button>
            </form>
            </div>
        </p>
    </div>
</nav>
<h1>WELCOME TO RAYUELA</h1>
<p>{{user.first_name}}</p>
{% block content_login %}
{% endblock %}
{% endblock %}

backend_rayuela/templates/pages/hopscotch.html
{% extends 'pages/home.html' %}
{% block content_login %}
<h1>HOPSCOTCH PAGE</h1>
{% if form %}
<div class="form-container" style=" width: 100%; display:flex; justify-content: center; margin-left: auto; margin-right: auto;">
    <form method="POST">
        <p>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="field-container" style="margin-top:2rem; margin-bottom: 2rem;">
                    <div>
                        {{ field.label_tag }}
                    </div>
                    <div>
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
        </p>
        <button class="button" type="submit">Crear rayuela</button>
    </form>
</div>
{% else %}
<div class="container-create" style="justify-content:center; display:flex ;width:100%;">
    <div class="button-logout">
        <form action="{% url 'hopscotch-urls:hopscotch-create' %}" method="POST">
            {% csrf_token %}
            <button type="submit">CREAR HISTORIA</button>
        </form>
    </div>
</div>
<div class="story_container" style="width: 100%; text-align:center;">
    <div class="for-container" style="display: inline-block; width: 45rem;">
        <h3>TUS RAYUELAS</h3>
    {% for hopscotch in hopscotchs %}
        <div class="container-hopscotch" style="padding: 1.5rem; margin-top: 3rem; text-align: left; border-style: solid; border-width: 1px; border-radius: 50px;">
            <div>{{ hopscotch.id }}- {{ hopscotch.title }}</div>

            <div>Información</div>
            <div>N° de participantes: 1</div>
            <div>Cantidad de historias: AGREGAR HOPSCOTCHSTORY PARA CALCULAR CANTIDAD</div>
            <div>Estado: {% if hopscotch.state %} Público {% else %} Privado {% endif %}</div>
            <div class="container-extra" style="justify-content: right; display:flex ;width:100%;">
                <div class="button-comentarios">
                    <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit">Comentarios</button>
                    </form>
                </div>
                 <div class="button-detalle-info">
                    <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit">Información detallada</button>
                    </form>
                </div>
                 <div class="button-detalle-info">
                    <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit">Invitar</button>
                    </form>
                </div>
            </div>

        </div>
    {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}

backend_rayuela/templates/pages/main_comments.html
<ul>
    {% include 'pages/all_comments.html' %}
</ul>

backend_rayuela/templates/pages/preview.html
{% extends 'pages/base.html' %}
{% block headline%}Bienvenido a Rayuela{% endblock %}

{% block content %}
<h1>BIENVENIDO A RAYUELA</h1>
     {% if user.is_anonymous %}

            <ul>
                <li>
                    <a href="{% url 'accounts-urls:login' %}">LOGIN</a>
                    <a href="{% url 'accounts-urls:create-user' %}">REGISTER</a>
                </li>
            </ul>
            {% block auth %}
            {% endblock %}
        {% else  %}
            <meta http-equiv="REFRESH" content="0;url={% url 'accounts-urls:writer-home' %}">
        {% endif %}
{% endblock %}

backend_rayuela/templates/pages/profile.html
{% extends 'pages/home.html' %}
{% block content_login %}
<h1>PROFILE PAGE</h1>
{% endblock %}

backend_rayuela/templates/pages/stories_routes.html
{% extends 'pages/home.html' %}
{% block content_login %}
<h1>STORIES ROUTES PAGE</h1>
{% if form %}
<div class="form-container" style=" width: 100%; display:flex; justify-content: center; margin-left: auto; margin-right: auto;">

    <form method="post">
        <p> 1° escoge tus historias y colaboradores
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="field-container" style="margin-top:2rem; margin-bottom: 2rem;">
                    <div>
                        {{ field.label_tag }}
                    </div>
                    <div>
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
        </p>
        <button class="button" type="submit">crear routa de historias</button>
    </form>
</div>
{% else %}
<div class="container-create" style="justify-content:center; display:flex ;width:100%;">
    <div class="button-logout">
        <form action="{% url 'stories-routes-urls:stories-routes-create' %}" method="POST">
            {% csrf_token %}
            <button type="submit">CREAR RUTA HISTORIA</button>
        </form>
    </div>
</div>
<div class="story_container" style="width: 100%; text-align:center;">
    <div class="for-container" style="display: inline-block; width: 45rem;">
        <h3>TUS RUTAS DE HISTORIAS</h3>
    {% for story_route in stories_routes %}
        <div class="container-hopscotch" style="padding: 1.5rem; margin-top: 3rem; text-align: left; border-style: solid; border-width: 1px; border-radius: 50px;">
            <div>{{ story_route.id }}</div>

            <div>Información</div>
            <div>N° de participantes: 1</div>
            <div>Cantidad de historias: AGREGAR HOPSCOTCHSTORY PARA CALCULAR CANTIDAD</div>
            <div>Estado: {% if story_route %} Público {% else %} Privado {% endif %}</div>
            <div class="container-extra" style="justify-content: right; display:flex ;width:100%;">
                <div class="button-comentarios">
                    <form action="{% url 'writers-urls:all-comments' %}" method="POST">
                    {% csrf_token %}
                    <button name="comments" value='{{ story_route.id }}' type="submit">Comentarios</button>
                    </form>
                </div>
                 <div class="button-detalle-info">
                    <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit">Información detallada</button>
                    </form>
                </div>
                 <div class="button-detalle-info">
                    <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit">Invitar</button>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}

backend_rayuela/templates/pages/story.html
{% extends 'pages/home.html' %}
{% block content_login %}
<h1>STORY PAGE</h1>

{% if form %}
<div class="form-container" style=" width: 100%; display:flex; justify-content: center; margin-left: auto; margin-right: auto;">
    <form method="POST">
        <p>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="field-container" style="margin-top:2rem; margin-bottom: 2rem;">
                    <div>
                        {{ field.label_tag }}
                    </div>
                    <div>
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
        </p>
        <button class="button" type="submit">Registrar</button>
    </form>
</div>
{% else %}
<div class="container-create" style="justify-content:center; display:flex ;width:100%;">
    <div class="button-logout">
        <form action="{% url 'stories-urls:story-create' %}" method="POST">
            {% csrf_token %}
            <button type="submit">CREAR HISTORIA</button>
        </form>
    </div>
</div>
<div class="story_container" style="width: 100%; text-align:center;">
    <div class="for-container" style="display: inline-block; width: 45rem;">

    {% for story in stories %}
     <div class="container" style="justify-content: center; display: flex; margin-top: 2rem; margin-bottom: 2rem; height: 15rem; border-style: solid; border-width: 1px; border-radius: 50px;">
        <div class="story" style="position: relative; width: 23rem; border-style: solid; border-width: 1px; border-radius: 50px;">
            <div class="title_story" style="margin-top: 2rem;">{{ story.title }}</div>
            <div class="body_story" style="text-align: justify; text-justify: inter-word; margin-top: 2rem;">{{ story.body }}</div>
            <small class="timestamp" style="text-align: right; position: absolute; bottom: 0;">{{ story.timestamp }}</small>
        </div>

        <div class="hashtag-container"  style=" width: 5rem; justify-content: center; flex-direction: column; margin-left: 5rem; margin-top: auto; margin-bottom: auto; border-style: solid; border-width: 1px; border-radius: 50px;">
          <p>HASHTAGS</p>
        {% for hashtag in story.hashtag_set.all %}
            <div class="hashtag" style="">{{ hashtag.hashtag }}</div>
        {% endfor %}

        </div>
     </div>
    {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}