backend_rayuela/accounts/urls.py
from django.urls import path
from .views import writer_home, writer_profile, create_user, view_profile, login_writer, logout_writer

app_name='accounts-urls'

urlpatterns = [
    path('', writer_home, name='writer-home'),
    path('profile/', writer_profile, name='writer-profile'),
    path('create/', create_user, name='create-user'),
    path('view-profile/<str:email>', view_profile, name='view-profile'),
    path('login/', login_writer, name='login'),
    path('logout/', logout_writer, name='logout'),
]

backend_rayuela/backend_rayuela/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import preview_page, login_page, logout_page

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', preview_page, name='init-page'),
    path('login/', login_page, name='login-page'),
    path('logout/', logout_page, name='logout-page'),
    path('story/', include('stories.urls', namespace='stories-urls')),
    path('writers/', include('writers.urls', namespace='writers-urls')),
    path('accounts/', include('accounts.urls', namespace='accounts-urls')),
    path('hopscotch', include('hopscotch.urls', namespace='hopscotch-urls')),
    path('stories-routes/', include('stories_routes.urls', namespace='stories-routes-urls'))
]


if settings.DEBUG:
    urlpatterns+= staticfiles_urlpatterns()

backend_rayuela/hopscotch/urls.py
from django.urls import path
from .views import hopscotch_home, hopscotch_create

app_name = 'hopscotch-urls'

urlpatterns = [
    path('home/', hopscotch_home, name='hopscotch-home'),
    path('create/', hopscotch_create, name='hopscotch-create')
]

backend_rayuela/stories/urls.py
from django.urls import path
from .views import story_home ,story_list, story_create, story_delete, story_detail, story_update, all_stories

app_name = 'stories-urls'

urlpatterns = [
    path('home/', story_home, name='story-home'),
    path('create/', story_create, name='story-create'),
    path('list/', story_list, name='story-list'),
    path('story/', story_detail, name='story-detail'),
    path('update/', story_update, name='story-update'),
    path('delete/', story_delete, name='story-delete'),
    path('all-stories', all_stories, name='all-stories')
]

backend_rayuela/stories_routes/urls.py
from django.urls import path
from .views import stories_routes_home, stories_routes_create, all_comments
app_name = 'stories-routes-urls'

urlpatterns=[
    path('home/', stories_routes_home, name='stories-routes-home'),
    path('create/', stories_routes_create, name='stories-routes-create'),
    path('all-comments/', all_comments, name='stories-routes-comments'),
]

backend_rayuela/templates/components/navbar.html
<nav class="nav">
    <ul class="nav-ul">
        <li class="nav-li">
            <a clas="nav-link" href="">HOME</a>
        </li>
        <li>
            <a class="nav-link" href="">STORIES</a>
        </li>
        <li>
            <a class="nav-link" href="{% url 'hopscotch-urls:hopscotch-home' %}">HOPSCOTCH</a>
        </li>
        <li>
            <a class="'nav-link" href="{% url 'stories-urls:stories-routes-home'%}">STORIES ROUTES</a>
        </li>
        <li>
            <a class="nav-link" href="{% url 'accounts-urls:writer-profile' %}">PROFILE</a>
        </li>
        <li>
            <form action="{% url 'accounts-urls:logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit">LOGOUT</button>
            </form>
        </li>
    </ul>
</nav>